asset_dir = "assets"
exclude_assets = []
write_dir = "src/shared"

[creator]
type = "group"
id = 5382451

[inputs.assets]
path = "assets/**/*"
output_path = "src/shared"

[codegen]
output_name = "assets"
typescript = true
style = "flat"
strip_extension = false
